apiVersion: v1
kind: ConfigMap
metadata:
  namespace: exercises
  name: log-output-config
data:
  information.txt: |
    This is a config file from ConfigMap for log-output application
    Exercise 2.5 - ConfigMaps and environment variables
