apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-lb
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
