apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todo-project-image-pvc
      containers:
        - name: todo-project
          image: todo-project:v1.13
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/files
