apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todo-project-image-pvc
      containers:
        - name: todo-project
          image: todo-project:v2.6.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-project-config
                  key: IMAGE_URL
            - name: IMAGE_REFRESH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: todo-project-config
                  key: IMAGE_REFRESH_INTERVAL
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/files
