apiVersion: v1
kind: Service
metadata:
  name: todo-project-svc
spec:
  type: NodePort
  selector:
    app: todo-project
  ports:
    - name: http
      protocol: TCP
      port: 3000          # Port inside cluster
      targetPort: 3000    # Port on the pod
      nodePort: 30080     # Port exposed on the node (30000-32767 range)
